### PR TITLE
Language Support

### PR DESCRIPTION
**Pull request by DarkerMinecraft**

### CODE REVIEW

**Comment by OfficialDonut** [comment]
The proper way to add language support is with [resource bundles](https://docs.oracle.com/javase/tutorial/i18n/resbundle/propfile.html).

Also, it won't be easy to use a language file to localize all of the individual text components of the blocks. While it would work for other text elements of the editor (e.g. menu text), I don't know if there's much point in only some of the text in the editor being localized.

**Comment by DarkerMinecraft** [comment]
How I have the system it shouldn't matter. It's like how Minecraft made their language files.

**Review by DarkerMinecraft — COMMENTED** [review]
OpenJFX Support

**Comment by OfficialDonut** [comment]
You should configure your IDE to use a JDK that includes JavaFX 8.

**Comment by OfficialDonut** [comment]
I am closing this PR because localization should be implemented properly with resource bundles and because the PR includes unrelated commits and random changes.

**Pull request closed without merging**
