### PR TITLE
Update GUI.properties

### PR DESCRIPTION
**Pull request by Sal4iDev**
People often confuse `Version` with `Server Version`, so you can rename this to `Plugin Version`

### CODE REVIEW

**Comment by Tofaa2** [comment]
Thats really their fault. Its literally the plugin file

**Comment by Sal4iDev** [comment]
> Thats really their fault. Its literally the plugin file 

Yes, I understand, just so that they do not get confused, this can be done

**Comment by Tofaa2** [comment]
why tho

**Comment by Sal4iDev** [comment]
> why tho
why not

**Pull request closed without merging**
